name = "blackwater"
license = "MIT"
licenselink = "https://github.com/jacobproffer/blackwater/blob/master/themes/blackwater/LICENSE"
description = "Arma 3 unit site for Blackwater USA."
homepage = "https://firstredsquadron.com/"
tags = ["military", "dark"]
features = ["sass", "js", "minification"]
min_version = "0.94.0"

[author]
  name = "Jacob Proffer"
  homepage = "https://proffer.dev/"
