baseURL = "http://example.org/"
languageCode = "en-us"
title = "Blackwater"
theme = "blackwater"

[params]
  subTitle = "The Premier Source for All of Your Security Services"
  description = "This is a starter shell for Hugo."

[menu]

  [[menu.main]]
    identifier = "Team"
    name = "Team"
    url = "/team/"
    weight = 1

  [[menu.main]]
    identifier = "Operations"
    name = "Operations"
    url = "/operations/"
    weight = 2

  [[menu.secondary]]
    identifier = "News"
    name = "News"
    url = "/news/"
    weight = 1

  [[menu.secondary]]
    identifier = "Media"
    name = "Media"
    url = "/media/"
    weight = 3
