baseURL = "https://blackwater.proffer.dev"
languageCode = "en-us"
title = "Blackwater"
theme = "blackwater"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
  subTitle = "The Premier Arma Unit for Your Security Services Needs"
  description = "Blackwater is an Arma unit focused on security and offensive operations."
  images = ["/images/blackwater-social.jpg"]

[menu]

  [[menu.main]]
    identifier = "Team"
    name = "Team"
    url = "/team/"
    weight = 1

  [[menu.main]]
    identifier = "Resources"
    name = "Resources"
    url = "/resources/"
    weight = 2

  [[menu.secondary]]
    identifier = "News"
    name = "News"
    url = "/news/"
    weight = 1

  [[menu.secondary]]
    identifier = "Media"
    name = "Media"
    url = "/media/"
    weight = 3
