baseURL = "https://blackwater.proffer.dev"
languageCode = "en-us"
title = "Blackwater"
theme = "blackwater"
pluralizelisttitles = "false"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
  subTitle = "The Premier Arma Unit for Your Security Services Needs"
  description = "Blackwater is an Arma unit focused on security and offensive operations."
  images = ["/images/blackwater-social.jpg"]

[menu]

  [[menu.main]]
    identifier = "Team"
    name = "Team"
    url = "/team/"
    weight = 1

  [[menu.main]]
    identifier = "Maps"
    name = "Maps"
    url = "/maps/"
    weight = 2

  [[menu.main]]
    identifier = "Resources"
    name = "Resources"
    url = "/resources/"
    weight = 3

  [[menu.main]]
    identifier = "News"
    name = "News"
    url = "/news/"
    weight = 4

  [[menu.social]]
    identifier = "Arma Unit"
    name = "Arma Unit"
    url = "https://units.arma3.com/unit/arma3blackwater"
    weight = 1

  [[menu.social]]
    identifier = "Steam Group"
    name = "Steam Group"
    url = "https://steamcommunity.com/groups/Arma3Blackwater"
    weight = 2

  [[menu.social]]
    identifier = "Mod Pack"
    name = "Mod Pack"
    url = "https://steamcommunity.com/sharedfiles/filedetails/?id=2027302046"
    weight = 3

  [[menu.mobile]]
    identifier = "Team"
    name = "Team"
    url = "/team/"
    weight = 1

  [[menu.mobile]]
    identifier = "Maps"
    name = "Maps"
    url = "/maps/"
    weight = 2

  [[menu.mobile]]
    identifier = "Intel"
    name = "Intel"
    url = "/intel/"
    weight = 3

  [[menu.mobile]]
    identifier = "News"
    name = "News"
    url = "/news/"
    weight = 4

