baseURL = "http://example.org/"
languageCode = "en-us"
title = "Blackwater"
theme = "blackwater"

[params]
  subTitle = "The Premier Source for All of Your Security Services"
  description = "This is a starter shell for Hugo."

[menu]

  [[menu.main]]
    identifier = "About"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "Operations"
    name = "Operations"
    url = "/operations/"
    weight = 2
