[build]
  publish = "public"
  command = "hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.94.0"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.94.0"

[context.deploy-preview]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[redirects]]
  from = "https://blackwater.proffer.dev/*"
  to = "https://firstredsquadron.com/"
  status = 301
  force = true

[[redirects]]
  from = "https://firstredsquadron.com/news/*"
  to = "https://firstredsquadron.com/:splat"
  status = 301
  force = true
