backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads"
collections:
  - name: "information"
    label: "Information"
    folder: "content/information"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Images", name: "images", widget: "list", field: {label: Image, name: image, widget: image}}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "news"
    label: "News"
    folder: "content/news"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Images", name: "images", widget: "list", field: {label: Image, name: image, widget: image}}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "team"
    label: "Team"
    folder: "content/team"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Position", name: "position", widget: "select", options: ["Aviation", "Medical", "Reconnassiance", "Security"]}
      - {label: "Level", name: "level", widget: "select", options: ["Command", "Contractor"]}
